### PR TITLE
add libdeflate, libpng, libjpegturbo and nghttp2

### PR DESCRIPTION
**Pull request by vincentsarago**
Dear Mr @perrygeo,
This PR adds libdeflate to the Tiff drivers which was recently added by Even. 

I also couldn't resist adding libjpeg turbo, libpng and nghttp2 🙈! 

Feel free to 🔪 this PR if you feel it's not needed for this project 😄

### CODE REVIEW

**Comment by vincentsarago** [comment]
Note:
I forgot but I also wanted to add some cleaning at the end of the dockerfile 

```
root@5bf0fd09ea28:/tmp# ls -la
total 54020
drwxrwxrwt  1 root root      4096 Feb 24 18:43 .
drwxr-xr-x  1 root root      4096 Feb 24 21:07 ..
-rw-r--r--  1 root root   2162983 Feb 24 17:48 2.0.5.tar.gz
drwxr-xr-x 14 1000  1000     4096 Feb 24 18:00 curl-7.73.0
-rw-r--r--  1 root root   4036697 Oct 14 05:53 curl-7.73.0.tar.gz
drwxrwxr-x 22 1000  1000     4096 Feb 24 18:43 gdal-3.2.1
-rw-r--r--  1 root root  18953600 Dec 29 12:31 gdal-3.2.1.tar.gz
drwxr-xr-x 11  501 staff     4096 Feb 24 17:49 geos-3.9.1
-rw-r--r--  1 root root   4761372 Feb 10 19:04 geos-3.9.1.tar.bz2
drwxrwxr-x  6 root root      4096 Feb 24 16:40 libdeflate-1.7
drwxrwxr-x 11 1000  1000     4096 Feb 24 18:08 libgeotiff-1.6.0
-rw-r--r--  1 root root    537175 Apr 24  2020 libgeotiff-1.6.0.tar.gz
drwxrwxr-x 13 root root      4096 Feb 24 17:49 libjpeg-turbo-2.0.5
drwxr-xr-x 13 _apt users     4096 Feb 24 16:39 libwebp-1.0.0
-rw-r--r--  1 root root   4023549 Apr 21  2018 libwebp-1.0.0.tar.gz
drwxr-xr-x 14 1000  1000     4096 Feb 24 17:59 nghttp2-1.42.0
-rw-r--r--  1 root root   4892226 Nov 23 15:00 nghttp2-1.42.0.tar.gz
drwxrwxr-x 11 root root      4096 Feb 24 18:08 openjpeg-2.3.1
-rw-r--r--  1 root root   2214401 Feb 24 18:08 openjpeg-2.3.1.tar.gz
drwxr-xr-x  9  501 staff     4096 Feb 24 18:00 proj-7.2.1
-rw-r--r--  1 root root   5714666 Jan  1 15:39 proj-7.2.1.tar.gz
drwxr-xr-x  5 1000  1000     4096 Feb 24 17:58 sqlite-autoconf-3330000
-rw-r--r--  1 root root   2913759 Nov 25 14:02 sqlite-autoconf-3330000.tar.gz
drwxr-xr-x 12 1107  5100     4096 Feb 24 17:58 tiff-4.2.0
-rw-r--r--  1 root root   2809373 Dec 19 18:41 tiff-4.2.0.tar.gz
-rw-r--r--  1 root root    144143 Feb 24 16:40 v1.7.tar.gz
drwxrwxr-x 10 root root      4096 Feb 24 16:40 zstd-1.3.4
-rw-r--r--  1 root root   2059958 Feb 24 16:40 zstd-1.3.4.tar.gz
```
Once we're done compiling we could get rid of all the stuff in `/tmp`

**Comment by perrygeo** [comment]
:pray: Thank you sir @vincentsarago. Good to work with you again ;-)  I'm excited to try out the HTTP2 support - [Your benchmarks](https://github.com/vincentsarago/gdal-http2-benchmark) look promising!

Originally I left the source files in the image so that I had access to them for debugging. I typically use this as a "builder" base image with a multistage docker build to remove all the cruft. But there's no need to have the tar.gz files _and_ the source tree. I'll at least clean up the tar file to save a little space.  :+1:

**Comment by vincentsarago** [comment]
> Thank you sir @vincentsarago. Good to work with you again ;-) I'm excited to try out the HTTP2 support - Your benchmarks look promising!

well in fact the benchmark was wrong 🤦 AWS S3 doesn't support multiplexing (http2), the gain seen in the benchmark was due to `GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES` ... which is natively available even for HTTP1 :-)

**Comment by perrygeo** [comment]
>  the gain seen in the benchmark was due to `GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES`

Still, I learned something new here :-) Thanks Vincent! 

Is there any reason not to turn that on by default?

**Comment by vincentsarago** [comment]
> Is there any reason not to turn that on by default?

Not that I know of. we set it by default almost everywhere ;-) 

https://github.com/developmentseed/titiler/blob/master/deployment/aws/cdk/app.py#L24-L26

Kyle started a doc over titiler explaining some of the GDAL configs https://github.com/developmentseed/titiler/blob/0a5288de30845865256a0124ed233f918812aa78/docs/concepts/performance_tuning.md

**Comment by vincentsarago** [comment]
> I typically use this as a "builder" base image with a multistage docker build to remove all the cruft

@perrygeo I hope my commit doesn't break your pipeline 😱. I usually install all the thing in a temp directory and then use `Origin` to make sure the lib a properly linked. You can check https://github.com/lambgeo/docker-lambda/blob/master/dockerfiles/gdal3.2/Dockerfile for example.

**Pull request merged**
